In [1]:
import numpy as np

In [4]:
#np.sum cu axis = 0 face suma pe coloane, axis = 1 pe linii
u = np.array([[2., -1., -2.], 
            [0., 4., 4.],
            [0., 0., 1.]])

n = np.shape(u)[0] # linii
n2 = np.shape(u)[1] # coloane

I = np.array([[1., 0., 0.], 
             [0., 1., 0.], 
             [0., 0., 1.]])
c = np.array([[-1.], 
              [8.], 
              [1.]])
x = np.array([[float('nan')], 
              [float('nan')], 
              [float('nan')]])
epsilon = 10**(-14)
# print(U)
# print(I)
# print(B)
if np.linalg.det(u) > epsilon:
    print("\nvarianta cu for")
    print("matricea este inversabila", np.linalg.det(u), ">", epsilon)
    
    for k in range(n-1, -1, -1):
        suma = 0
        for j in range(k+1, n):
            suma = suma + (u[k][j]*x[j])
        x[k] = (c[k] - suma) / u[k][k]
            
    print("solutia este\n", x)
    print(u@x) # inmultire matrice
    
    print("------------\nvarianta cu np.dot")
    x = np.array([[float('nan')], 
                  [float('nan')], 
                  [float('nan')]])
    
    for k in range(n-1, -1, -1):
        x[k] = (c[k] - np.dot(u[k][k+1 : ], x[k+1 : ])) / u[k][k]
            
    print("solutia este\n", x)
    print(u@x) # inmultire matrice


varianta cu for
matricea este inversabila 7.999999999999998 > 1e-14
solutia este
 [[1.]
 [1.]
 [1.]]
[[-1.]
 [ 8.]
 [ 1.]]
------------
varianta cu np.dot
solutia este
 [[1.]
 [1.]
 [1.]]
[[-1.]
 [ 8.]
 [ 1.]]


In [60]:
print(u[2 :])
print(x[:2])

[[0. 0. 1.]]
[[1 2]
 [3 4]]


In [63]:
u = np.array([[2., -1., -2.], 
            [0., 4., 4.],
            [0., 0., 1.]])

n = np.shape(u)[0] # linii
n2 = np.shape(u)[1] # coloane

I = np.array([[1., 0., 0.], 
             [0., 1., 0.], 
             [0., 0., 1.]])
c = np.array([[-1.], 
              [8.], 
              [1.]])
x = np.array([[float('nan')], 
              [float('nan')], 
              [float('nan')]])
epsilon = 10**(-14)
if np.linalg.det(U) > epsilon:
    print("matricea este inversabila", np.linalg.det(U), ">", epsilon)
    x[n-1] = c[n-1] / u[n-1][n-1]
    
    for k in range(n-2, -1, -1):
        x[k] = (c[k] - np.dot(u[k][k+1 : n], x[k+1 : n])) / u[k][k]
            
    print(x)
    print(u@x) # inmultire matrice
    
    


matricea este inversabila 7.999999999999998 > 1e-14
[[1.]
 [1.]
 [1.]]
[[-1.]
 [ 8.]
 [ 1.]]


In [48]:
x = np.array([[1, 2],[3, 4]])
y = np.array([[5, 6],[7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
# vector x vector => 219
print(v.dot(w))
print(np.dot(v, w))
# matrice x vector => [29 67]
print(np.matmul(x, v))
# matrice x matrice => [[19 22]
# [43 50]]
print(np.matmul(x, y))

219
219
[29 67]
[[19 22]
 [43 50]]


In [50]:
99+120

219