In [5]:
import numpy as np
"""def gfp_lu(aext):
    n = np.shape(aext)[0] # nr linii
    L = np.identity(n) # matricea identitate
    for k in range(n-1):
        for l in range(k+1, n): 
            scalar = aext[l][k] / aext[k][k]
            aext[l] = aext[l] - scalar * aext[k]
            L[l][k] = scalar
    return aext, L"""

def gfp_lu(u):
    n = np.shape(u)[0] # nr linii
    L = np.identity(n) # matricea identitate
    for k in range(n-1):
        L[k+1:, k] = u[k+1:, k] / u[k, k]
        u[k+1:, k:] -= np.outer(L[k+1:, k], u[k, k:]) # np.outer(scalar, linia k)
    return u, L

a = np.array([[2., -1., -2.], 
             [4., 2., 0.], 
             [0., -2., -1.]])
u = np.copy(a)
det = np.linalg.det(a)
if np.abs(det) < 1e-14:
    print("sistemul nu are solutie(matr nu este inversabila)")
else:
    u, l = gfp_lu(u)
    print("L=")
    print(l)
    print("U=")
    print(u)
    print("L*U=")
    print(l@u)

L=
[[ 1.   0.   0. ]
 [ 2.   1.   0. ]
 [ 0.  -0.5  1. ]]
U=
[[ 2. -1. -2.]
 [ 0.  4.  4.]
 [ 0.  0.  1.]]
L*U=
[[ 2. -1. -2.]
 [ 4.  2.  0.]
 [ 0. -2. -1.]]


In [11]:
import numpy as np
def gpp_lu(a):
    n = np.shape(a)[0] # nr linii
    # initializare  
    P = np.identity(n)
    U = np.copy(a)
    L = np.zeros(shape = (n, n))
    
    for k in range(n-1):
        p = np.argmax(np.abs(U[k:, k])) 
        p += k # adaug offsetul

        # swap linia p cu linia k
        U[[p, k]] = U[[k, p]] 
        P[[p, k]] = P[[k, p]]
        L[[p, k]] = L[[k, p]]

        # definire L, U ca in gfp_lu
        L[k+1:, k] = U[k+1:, k] / U[k, k]
        U[k+1:, k:] -= np.outer(L[k+1:, k], U[k, k:])
           
    L += np.identity(n)
    return P, L, U

def SubsDesc(u, c,  epsilon = 10**(-14)):
    if abs(np.linalg.det(u)) > epsilon:
        n = np.shape(u)[0] # nr linii
        x = np.array([[float('nan')]] * n) # initalizez solutia cu 'nan' pt n linii
        for k in range(n-1, -1, -1):
            x[k] = (c[k] - np.dot(u[k][k+1 : ], x[k+1 : ])) / u[k][k]
        return x

def SubsAsc(u, c,  epsilon = 10**(-14)):
    if abs(np.linalg.det(u)) > epsilon:
        n = np.shape(u)[0] # nr linii
        x = np.array([[float('nan')]] * n) # initalizez solutia cu 'nan' pt n linii
        for k in range(n):
            x[k] = (c[k] - np.dot(u[k][ : k], x[: k])) / u[k][k]
        return x

a = np.array([[1., 2., 3.], 
              [4., 5., 6.], 
              [7., 8., 10.]])

det = np.linalg.det(a)
if np.abs(det) < 1e-14:
    print("sistemul nu are solutie(matr nu este inversabila)")
else:
    p, l, u = gpp_lu(a) # calcul p, l, u
#     print("P=", p)
#     print("L=", l)
#     print("U=", u)
#     print("P@A=", p@a)
#     print("L@U=", l@u)
    b = np.array([[4], [4], [7]]) 
    y = SubsAsc(l, p@b) 
    x = SubsDesc(u, y)
    # verificare : a@x = b
    print("a@x=", a@x)

a@x= [[4.]
 [4.]
 [7.]]
