In [3]:
# ex 1 
# Sa se verifice daca sistemul (1) admite solutie unica si ın caz afirmativ sa se determine solutia folosind metoda
# Gauss cu pivotare totala.
import numpy as np

def gpt(aext, index):
    n = np.shape(aext)[0] # nr linii
    for k in range(n-1):
        #M: Trebuie maximum doar de la linia si coloana k incolo
        p, m = np.unravel_index(aext[k:, k:n].argmax(), aext[k: ,k:n].shape) # returns a tuple
        p += k # adaug offsetul
        m += k
        aext[[p, k]] = aext[[k, p]] # swap linia p cu linia k
        aext[:,[m, k]] = aext[:,[k, m]] # swap coloana m cu coloana k
        index[m], index[k] = index[k], index[m] # pt necunoscute
        for l in range(k+1, n):
            aext[l] = aext[l] - (aext[l][k] / aext[k][k]) * aext[k] 
    return aext, index

def SubsDesc(u, c,  epsilon = 10**(-14)):
    if abs(np.linalg.det(u)) > epsilon: # matricea este inversabila
        n = np.shape(u)[0] # nr linii
        x = np.array([[float('nan')]] * n)
        for k in range(n-1, -1, -1):
            x[k] = (c[k] - np.dot(u[k][k+1 : ], x[k+1 : ])) / u[k][k] # rezolv sistemul (de la ultima la prima linie)
    return x

a = np.array([[0., -6., 7., 9.],  # sistemul meu
             [1., -2., 2., -3.], 
             [-8., 1., -4., -4.],
             [0., -6., -10., -2.]])
n = a.shape[0] # nr linii
b = np.array([[65.], 
             [-13.], 
             [-64.],
             [-86.]])

"""a = np.array([[0., -3., -8., 7.],  # alt sistem din tema unui coleg 
             [-1., 5., 9., 2.], 
             [-8., 5., -9., 9.],
             [8., -6., -5., -2.]])
n = a.shape[0] # nr linii
b = np.array([[-14.], 
             [89.], 
             [2.],
             [-42.]])"""

det = np.linalg.det(a) # determinantul
if np.abs(det) < 1e-14:
    print("sistemul nu are solutie(matr nu este inversabila)")
else:     
    index = [i for i in range(n)] # lista indecsi
    aext = np.hstack((a,b)) # construire a extins
    aext, index = gpt(aext, index) # aplic metoda gauss cu pivotare totala
    print('a\n',a,'\naext dupa gpt\n',aext, '\nb\n', b)
    print('index\n', index)
    c = aext[:, [n]] # ultima coloana din aext; vector coloana
    u = aext[:, :n] # primele n coloane
    print('c\n', c)
    print('u\n', u)
    x = SubsDesc(u, c) # calculez solutia cu subsdesc(u, c)
    #x = x[index] #M: Reordonez x !!!!!!!!!!!!!!!!!!
    sol = np.copy(x) """La exercitiul 1 metoda este buna mai putin ordinea necunoscutelor, se pare ca acel x = x[index]
                        nu merge bine pentru un numar mai complex de permutari. Iti propun urmatoare solutie pentru 
                        aceasta reordonare:
                        sol = np.copy(x)
                        sol[index] = x."""
    sol[index] = x
    print("solutia este\n", sol)
    #M: Verificare
    print('a@x\n',a @ sol) #M: Trebuie sa dea egal cu b 
    # valorile sunt putin diferite fata de cele initiale din b.. nu am observat vreo eroare prin cod (a functionat si pe 
    # sistemul de la laborator)
    # am incercat si pe un sistem de la un coleg (cel comentat mai sus), iar rezultatul a fost ok

a
 [[  0.  -6.   7.   9.]
 [  1.  -2.   2.  -3.]
 [ -8.   1.  -4.  -4.]
 [  0.  -6. -10.  -2.]] 
aext dupa gpt
 [[   9.            7.            0.           -6.           65.        ]
 [   0.            4.33333333    1.           -4.            8.66666667]
 [   0.            0.            1.94871795  -15.12820513  -54.66666667]
 [   0.            0.            0.          -63.         -252.        ]] 
b
 [[ 65.]
 [-13.]
 [-64.]
 [-86.]]
index
 [3, 2, 0, 1]
c
 [[  65.        ]
 [   8.66666667]
 [ -54.66666667]
 [-252.        ]]
u
 [[  9.           7.           0.          -6.        ]
 [  0.           4.33333333   1.          -4.        ]
 [  0.           0.           1.94871795 -15.12820513]
 [  0.           0.           0.         -63.        ]]
solutia este
 [[3.]
 [4.]
 [5.]
 [6.]]
a@x
 [[ 65.]
 [-13.]
 [-64.]
 [-86.]]


In [2]:
# ex 2
# Verificati daca matricea B este inversabila si in caz afirmativ aplicati metoda Gauss pentru determinarea inversei.

b = np.array([[0., 2., 2., 7.],  # matricea b
             [-4., -4., 2., 0.], 
             [-8., -1., 0., -5.],
             [-4., -5., -7., -2.]])
det = np.linalg.det(b) # determinantul matricei

if np.abs(det) < 1e-14:
    print("matricea nu este inversabila")
else:   
    print("matricea este inversabila")
    n = b.shape[0] # nr linii
    i4 = np.identity(n) # matricea identitate i4
    bext = np.concatenate((b, i4), axis = 1) # concatenez matrcea identitate la dreapta lui b
    print('b ext\n', bext)
    index = [i for i in range(n)] # lista indecsi
    bext, index = gpt(bext, index) # aplic metoda gauss cu pivotare totala pt matricea de dimensiune n x 2n
    print('b ext dupa gpt')
    with np.printoptions(precision=3, suppress=True): # pt afisare mai ok
        print(bext)

    # obtin n sisteme cu n necunoscute pe care le rezolv cu subsdesc
    u = bext[:, :n] # primele n coloane (u este matrice superior triunghiulara)
    print('u\n', u)
    b1 = np.empty((n, n))  # inversa matricei, va fi calculata ulterior 
    for i in range(n): # parcurg sistemele
        c = bext[:, [i+n]] #coloana i + n din b(bInitial+matrIdentitate); vector coloana
#         print('c\n', c)
        x = SubsDesc(u, c) # calculez solutia cu subsdesc(u, c)
        x = x[index] # reordonare solutii
        b1[:, [i]] = x # actualizare coloana i din inversa matricei 
    print('inversa matricei este b1\n', b1)
    print('verificare b@b1\n', b@b1) # b@b1 = i4

matricea este inversabila
b ext
 [[ 0.  2.  2.  7.  1.  0.  0.  0.]
 [-4. -4.  2.  0.  0.  1.  0.  0.]
 [-8. -1.  0. -5.  0.  0.  1.  0.]
 [-4. -5. -7. -2.  0.  0.  0.  1.]]
b ext dupa gpt
[[  7.      2.      2.      0.      1.      0.      0.      0.   ]
 [  0.      2.     -4.     -4.      0.      1.      0.      0.   ]
 [  0.      0.      3.286  -5.143   0.714  -0.714   1.      0.   ]
 [  0.      0.      0.    -43.913   4.043  -0.543   5.261   1.   ]]
u
 [[  7.           2.           2.           0.        ]
 [  0.           2.          -4.          -4.        ]
 [  0.           0.           3.28571429  -5.14285714]
 [  0.           0.           0.         -43.91304348]]
inversa matricei este b1
 [[-0.09207921  0.01237624 -0.11980198 -0.02277228]
 [ 0.07326733 -0.1980198   0.11683168 -0.03564356]
 [-0.03762376  0.12871287 -0.00594059 -0.11683168]
 [ 0.13267327  0.01980198 -0.03168317  0.04356436]]
verificare b@b1
 [[ 1.00000000e+00  0.00000000e+00  1.38777878e-17  0.00000000e+00]
 [ 

In [3]:
# ex 3
# Sa se verifice daca sistemul (3) admite solutie unica si ın caz afirmativ sa se determine solutia folosind factorizarea
# LU cu pivotare partiala.
def gpp_lu(a):
    n = np.shape(a)[0] # nr linii
    # initializare  
    P = np.identity(n)
    U = np.copy(a)
    L = np.zeros(shape = (n, n))
    
    for k in range(n-1):
        p = np.argmax(np.abs(U[k:, k])) # indice maxim pe coloana
        p += k # adaug offsetul

        # swap linia p cu linia k
        U[[p, k]] = U[[k, p]] 
        P[[p, k]] = P[[k, p]]
        L[[p, k]] = L[[k, p]]

        # definire L, U ca in gfp_lu
        L[k+1:, k] = U[k+1:, k] / U[k, k]
        U[k+1:, k:] -= np.outer(L[k+1:, k], U[k, k:])
           
    L += np.identity(n)
    return P, L, U

def SubsAsc(u, c,  epsilon = 10**(-14)):
    if abs(np.linalg.det(u)) > epsilon: # matr inversabila
        n = np.shape(u)[0] # nr linii
        x = np.array([[float('nan')]] * n) # initalizez solutia cu 'nan' pt n linii
        for k in range(n):
            x[k] = (c[k] - np.dot(u[k][ : k], x[: k])) / u[k][k] # rezolv sistemul (de la prima la ultima linie)
        return x
    
a = np.array([[0., -3., 4., 6.],  # matricea a
             [9., -3., 4., -6.], 
             [4., 4., -9., -1.],
             [1., -3., -9., 5.]])
b = np.array([[30.], 
             [-9.], 
             [-19.],
             [-12.]])
det = np.linalg.det(a)
if np.abs(det) < 1e-14:
    print("sistemul nu are solutie(matr nu este inversabila)")
else:
    # ax = b <=> pax = pb <=> lux = pb (deoarece pa = lu). notez y = ux => ly = pb => y = .. subsc asc
    #                                                                   => x = .. subs desc 
    p, l, u = gpp_lu(a) # calcul p, l(inferior triunghiulara), u(superior triunghiulara)
    print("P=\n", p)
    print("L=\n", l)
    print("U=\n", u)
    print("P@A=\n", p@a) # p@a == l@u == a' (liniile sunt permutate)
    print("L@U=\n", l@u)
    y = SubsAsc(l, p@b) # rezolv sistemul ly = pb cu subs asc
    x = SubsDesc(u, y) # rezolv sistemul y = ux cu subs desc
    # verificare : a@x = b
    print("verificare\na@x=\n", a@x)

P=
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
L=
 [[ 1.          0.          0.          0.        ]
 [ 0.44444444  1.          0.          0.        ]
 [ 0.11111111 -0.5         1.          0.        ]
 [ 0.         -0.5625      0.13904494  1.        ]]
U=
 [[  9.          -3.           4.          -6.        ]
 [  0.           5.33333333 -10.77777778   1.66666667]
 [  0.           0.         -14.83333333   6.5       ]
 [  0.           0.           0.           6.03370787]]
P@A=
 [[ 9. -3.  4. -6.]
 [ 4.  4. -9. -1.]
 [ 1. -3. -9.  5.]
 [ 0. -3.  4.  6.]]
L@U=
 [[ 9. -3.  4. -6.]
 [ 4.  4. -9. -1.]
 [ 1. -3. -9.  5.]
 [ 0. -3.  4.  6.]]
verificare
a@x=
 [[ 30.]
 [ -9.]
 [-19.]
 [-12.]]


In [4]:
# ex 4
# Sa se verifice daca matricea C admite factorizare Cholesky si ın caz afirmativ sa se determine aceasta.

from math import sqrt

def poz_def(matrix):
    n = matrix.shape[0]
    for i in range(n):
        minor = matrix[:i+1, :i+1] # extrag fiecare minor din matrice
        if np.linalg.det(minor) < 0: # daca det(minor) e negativ atunci matricea nu e poz def
            return False
    return True

def factorizare_Cholesky(a, b = None):
    # pas 1
    alpha = a[0][0]
    if alpha <= 0:
        print('matricea nu este pozitiv definita')
        return None 
    
    n = a.shape[0] # nr linii matrice a
    l = np.zeros((n, n)) # matrice de n x n, empty
    l[0][0] = sqrt(a[0][0]) # primul element de pe diagonala
    
    for i in range(1, n): # se determina celelalte elemente de pe prima coloana
        l[i][0] = a[i][0] / l[0][0]
    
    # pas 2
    for k in range(1, n): # elem de pe coloana k
        sum = 0
        for s in range(0, k):
            sum += l[k][s] ** 2
        alpha = a[k][k] - sum
        if alpha <= 0:
            print('matricea nu este pozitiv definita')
            return None 
        
        l[k][k] = sqrt(alpha) # elementul de pe diagonala principala 
        
        for i in range(k+1, n): # restul elementelor de pe coloana k
            sum = 0
            for s in range(0, k):
                sum += l[i][s] * l[k][s]
            l[i][k] = (a[i][k] - sum) / l[k][k]
            
    if b != None: # am un sistem de rezolvat
        # pas 3 
        y = SubsAsc(l, b) # rezolv sistemul ly = b cu subs asc

        # pas 4
        x = SubsDesc(l.T, y) # rezolv sistemul l.Tx = y cu subs desc
    
        return l, x # factorizarea l + solutia daca rezolv un sistem cu metoda cholesky
    
    return l # doar factorizarea
    
c = np.array([[36., -18., -48., -42.],  # matricea c
             [-18., 45., 0., 27.], 
             [-48., 0., 84., 62.],
             [-42., 27., 62., 124.]])

if (poz_def(c) == False) | (c != c.T).any():
    print("matricea c nu este simetrica si pozitiv definita")
else:
    print("factorizarea cholesky:")
    l = factorizare_Cholesky(c)
    print(l)
    print('verificare l@l.T\n', l@l.T) # l@l.T = c 

factorizarea cholesky:
[[ 6.  0.  0.  0.]
 [-3.  6.  0.  0.]
 [-8. -4.  2.  0.]
 [-7.  1.  5.  7.]]
verificare l@l.T
 [[ 36. -18. -48. -42.]
 [-18.  45.   0.  27.]
 [-48.   0.  84.  62.]
 [-42.  27.  62. 124.]]
