In [1]:
import numpy as np

a = np.array([[2., -1., -2.], 
             [4., 2., 0.], 
             [0., -2., -1.]])
b = np.array([[-1.], 
             [6.], 
             [-3.]])
aext = np.concatenate((a, b), axis = 1) # matricea extinsa
# aext = np.hstack((a,b))
n = np.shape(aext)[0] # linii

# gfp
def gfp(aext):
    n = np.shape(aext)[0] # nr linii
    for k in range(n-1):
        for l in range(k+1, n): # *********************
            aext[l] = aext[l] - (aext[l][k] / aext[k][k]) * aext[k]
    return aext

def SubsDesc(u, c,  epsilon = 10**(-14)):
    if abs(np.linalg.det(u)) > epsilon:
        n = np.shape(u)[0] # nr linii
        for k in range(n-1, -1, -1):
            x[k] = (c[k] - np.dot(u[k][k+1 : ], x[k+1 : ])) / u[k][k]
    return x

aext = gfp(aext) # aplic metoda gauss fara pivotare
print(aext)       

c = aext[:, [n]] # ultima coloana din aext; vector coloana
u = aext[:, :n] # primele n coloane

x = np.array([[float('nan')], 
              [float('nan')], 
              [float('nan')]])

x = SubsDesc(u, c) # calculez solutia cu subsdesc(u, c)
            
print("solutia este\n", x)
# if False in u@x == c:
#     print('gresit')
# else:
#     print('corect')

[[ 2. -1. -2. -1.]
 [ 0.  4.  4.  8.]
 [ 0.  0.  1.  1.]]
solutia este
 [[1.]
 [1.]
 [1.]]


In [3]:
def gpp(aext):
    n = np.shape(aext)[0] # nr linii
    for k in range(n-1):
        for l in range(k+1, n):
            p = np.argmax(aext[:, k]) # indicele elem maxim de pe col k in jos 
            p += k # adaug offsetul
            aext[[p, k]] = aext[[k, p]] # swap linia p cu linia k
            aext[l] = aext[l] - (aext[l][k] / aext[k][k]) * aext[k] 
    return aext

a = np.array([[2., -1., -2.], 
             [4., 2., 0.], 
             [0., -2., -1.]])
n = a.shape[0] # nr linii
b = np.array([[-1.], 
             [6.], 
             [-3.]])
aext = np.hstack((a,b)) # construire a extins
aext = gpp(aext) # aplic metoda gauss cu pivotare
print('a\n',a,'\naext dupa gpp\n',aext)

c = aext[:, [n]] # ultima coloana din aext; vector coloana
u = aext[:, :n] # primele n coloane
x = np.array([[float('nan')], 
              [float('nan')], 
              [float('nan')]])

x = SubsDesc(u, c) # calculez solutia cu subsdesc(u, c)
            
print("solutia este\n", x)

a
 [[ 2. -1. -2.]
 [ 4.  2.  0.]
 [ 0. -2. -1.]] 
aext dupa gpp
 [[ 4.  2.  0.  6.]
 [ 0. -2. -2. -4.]
 [ 0.  0.  1.  1.]]
solutia este
 [[1.]
 [1.]
 [1.]]


In [47]:
# pt matricea cu epsilon
b = np.array([[1.], 
              [2.]])
x = np.array([[float('nan')], 
                  [float('nan')]])
for k in range(1, 20):
    eps = 10**(-k)
    a = np.array([[eps, 1.],
             [1., 1.]])
    aext = np.concatenate((a, b), axis = 1) # matricea extinsa
    n = np.shape(aext)[0] # linii
    aext = gpp(aext) # aplic metoda gauss fara pivotare
    c = aext[:, [n]] # ultima coloana din aext; vector coloana
    u = aext[:, :n] # primele n coloane
    x = SubsDesc(u, c)
    print('solutia pentru k=', k, 'este')
    print(x) 

solutia pentru k= 1 este
[[1.11111111]
 [0.88888889]]
solutia pentru k= 2 este
[[1.01010101]
 [0.98989899]]
solutia pentru k= 3 este
[[1.001001]
 [0.998999]]
solutia pentru k= 4 este
[[1.00010001]
 [0.99989999]]
solutia pentru k= 5 este
[[1.00001]
 [0.99999]]
solutia pentru k= 6 este
[[1.000001]
 [0.999999]]
solutia pentru k= 7 este
[[1.0000001]
 [0.9999999]]
solutia pentru k= 8 este
[[1.00000001]
 [0.99999999]]
solutia pentru k= 9 este
[[1.]
 [1.]]
solutia pentru k= 10 este
[[1.]
 [1.]]
solutia pentru k= 11 este
[[1.]
 [1.]]
solutia pentru k= 12 este
[[1.]
 [1.]]
solutia pentru k= 13 este
[[1.]
 [1.]]
solutia pentru k= 14 este
[[1.]
 [1.]]
solutia pentru k= 15 este
[[1.]
 [1.]]
solutia pentru k= 16 este
[[1.]
 [1.]]
solutia pentru k= 17 este
[[1.]
 [1.]]
solutia pentru k= 18 este
[[1.]
 [1.]]
solutia pentru k= 19 este
[[1.]
 [1.]]


In [4]:
def gpt(aext, index):
    n = np.shape(aext)[0] # nr linii
    for k in range(n-1):
        for l in range(k+1, n):
            p, m = np.unravel_index(aext.argmax(), aext.shape) # returns a tuple
            p += k # adaug offsetul
            m += k
            aext[[p, k]] = aext[[k, p]] # swap linia p cu linia k
            aext[:,[m, k]] = aext[:,[k, m]] # swap coloana m cu coloana k
            index[m], index[k] = index[k], index[m] # pt necunoscute
            aext[l] = aext[l] - (aext[l][k] / aext[k][k]) * aext[k] 
    return aext, index
a = np.array([[1., 2., 3.], 
             [4., 5., 6.], 
             [7., 8., 9.]])
n = a.shape[0] # nr linii
b = np.array([[4.], 
             [4.], 
             [7.]])
index = [i for i in range(n)]
aext = np.hstack((a,b)) # construire a extins
aext, index = gpt(aext, index) # aplic metoda gauss cu pivotare
print('a\n',a,'\naext dupa gpt\n',aext)
print('index\n', index)
c = aext[:, [n]] # ultima coloana din aext; vector coloana
u = aext[:, :n] # primele n coloane
x = np.array([[float('nan')], 
              [float('nan')], 
              [float('nan')]])
x = SubsDesc(u, c) # calculez solutia cu subsdesc(u, c)
print("solutia este\n", x)

a
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 
aext dupa gpt
 [[ 9.          8.          7.          7.        ]
 [ 0.         -0.33333333 -0.66666667 -0.66666667]
 [ 0.          0.          0.          3.        ]]
index
 [2, 1, 0]
solutia este
 [[nan]
 [nan]
 [nan]]


In [18]:
#M: Modificata de mine
def gpt(aext, index):
    n = np.shape(aext)[0] # nr linii
    for k in range(n-1):
        #M: Pune cautarea pivotului si interschimbarea in for-ul mare, pe coloane, sa modifici si la pivotarea partiala, 
        # nu iti genereaza erori dar e time-consuming grav
        p, m = np.unravel_index(aext[k:,k:n].argmax(), aext[k:,k:n].shape) # returns a tuple #M: Trebuie maximum doar de la linia si coloana k incolo
        p += k # adaug offsetul
        m += k
        aext[[p, k]] = aext[[k, p]] # swap linia p cu linia k
        aext[:,[m, k]] = aext[:,[k, m]] # swap coloana m cu coloana k
        index[m], index[k] = index[k], index[m] # pt necunoscute
        for l in range(k+1, n):
            aext[l] = aext[l] - (aext[l][k] / aext[k][k]) * aext[k] 
    return aext, index
a = np.array([[1., 2., 3.], 
             [4., 5., 6.], 
             [7., 8., 10.]]) #M: Elementul din colt e 10, nu 9, altfel matricea nu e inversabila si nu poti rezolva sistemul. 
                             #Adauga conditia ca matricea sa fie inversabila la inceputul metodelor Gauss ca sa te pazesti pe viitor
n = a.shape[0] # nr linii
b = np.array([[4.], 
             [4.], 
             [7.]])
index = [i for i in range(n)]
aext = np.hstack((a,b)) # construire a extins
aext, index = gpt(aext, index) # aplic metoda gauss cu pivotare
print('a\n',a,'\naext dupa gpt\n',aext)
print('index\n', index)
c = aext[:, [n]] # ultima coloana din aext; vector coloana
u = aext[:, :n] # primele n coloane
x = np.array([[float('nan')], 
              [float('nan')], 
              [float('nan')]])
x = SubsDesc(u, c) # calculez solutia cu subsdesc(u, c)
x = x[index] #M: Reordonez x
print("solutia este\n", x)
#M: Verificare
print(a @ x) #M: Trebuie sa dea egal cu b = [4 4 7]

a
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. 10.]] 
aext dupa gpt
 [[10.   8.   7.   7. ]
 [ 0.   0.2 -0.2 -0.2]
 [ 0.   0.  -1.5  1.5]]
index
 [2, 1, 0]
solutia este
 [[-1.]
 [-2.]
 [ 3.]]
[[4.]
 [4.]
 [7.]]
