# 1. Inversa unei matrici 
### metoda Gauss cu pivotare totala

In [1]:
import numpy as np

def gpt(aext, index):
    n = np.shape(aext)[0] # nr linii
    for k in range(n-1):
        # Trebuie maximum doar de la linia si coloana k incolo
        p, m = np.unravel_index(aext[k:, k:n].argmax(), aext[k: ,k:n].shape) # returns a tuple
        p += k # adaug offsetul
        m += k
        aext[[p, k]] = aext[[k, p]] # swap linia p cu linia k
        aext[:,[m, k]] = aext[:,[k, m]] # swap coloana m cu coloana k
        index[m], index[k] = index[k], index[m] # pt necunoscute
        for l in range(k+1, n):
            aext[l] = aext[l] - (aext[l][k] / aext[k][k]) * aext[k] 
    return aext, index

def SubsDesc(u, c,  epsilon = 10**(-14)):
    if abs(np.linalg.det(u)) > epsilon: # matricea este inversabila
        n = np.shape(u)[0] # nr linii
        x = np.array([[float('nan')]] * n)
        for k in range(n-1, -1, -1):
            x[k] = (c[k] - np.dot(u[k][k+1 : ], x[k+1 : ])) / u[k][k] # rezolv sistemul (de la ultima la prima linie)
    return x

def inverse(b):
    n = b.shape[0] # nr linii
    i4 = np.identity(n) # matricea identitate i4
    bext = np.concatenate((b, i4), axis = 1) # concatenez matrcea identitate la dreapta lui b
    index = [i for i in range(n)] # lista indecsi
    bext, index = gpt(bext, index) # aplic metoda gauss cu pivotare totala pt matricea de dimensiune n x 2n

    # obtin n sisteme cu n necunoscute pe care le rezolv cu subsdesc
    u = bext[:, :n] # primele n coloane (u este matrice superior triunghiulara)
    b1 = np.empty((n, n))  # inversa matricei, va fi calculata ulterior 
    for i in range(n): # parcurg sistemele
        c = bext[:, [i+n]] #coloana i + n din b(bInitial+matrIdentitate); vector coloana
        x = SubsDesc(u, c) # calculez solutia cu subsdesc(u, c)
        x = x[index] # reordonare solutii
        b1[:, [i]] = x # actualizare coloana i din inversa matricei 
    
    return b1

b = np.array([[0., 2., 2., 7.],  # matricea b
             [-4., -4., 2., 0.], 
             [-8., -1., 0., -5.],
             [-4., -5., -7., -2.]])
det = np.linalg.det(b) # determinantul matricei

if np.abs(det) < 1e-14:
    print("matricea nu este inversabila")
else:   
    print("matricea este inversabila")
    b1 = inverse(b)
    print('inversa matricei b este b1\n', b1)
#     print('verificare b@b1\n', b@b1) # b@b1 = i4

matricea este inversabila
inversa matricei b este b1
 [[-0.09207921  0.01237624 -0.11980198 -0.02277228]
 [ 0.07326733 -0.1980198   0.11683168 -0.03564356]
 [-0.03762376  0.12871287 -0.00594059 -0.11683168]
 [ 0.13267327  0.01980198 -0.03168317  0.04356436]]


# Lema substitutiei

In [2]:
b = np.array([[1, 0, 0],  # matricea b
             [0, 2, 0], 
             [0, 0, 1]])
n = b.shape[0]

b1 = inverse(b) # inversa lui b

c = np.array([2, 1, 1])

k = 1

btilda = b.copy()
btilda[:, k] = c # coloana k = c

y = b1 @ c # vector coloana

eta = -y / y[k]
eta[k] = 1 / y[k]

ek = np.eye(n) # matrice identitate
ek[:,k] = eta # coloana k este inlocuita cu eta

btilda1 = ek @ b1
print("inversa lui btilda este:\n", btilda1)

inversa lui btilda este:
 [[ 1. -2.  0.]
 [ 0.  1.  0.]
 [ 0. -1.  1.]]


In [8]:
b = np.array([[5, 0, 0],  # matricea b
             [0, 2, 0], 
             [0, 0, 3]])
n = b.shape[0]

b1 = inverse(b) # inversa lui b

c = np.array([1, 1, 2])

k = 1

btilda = b.copy()
btilda[:, k] = c # coloana k = c

y = b1 @ c # vector coloana

eta = -y / y[k]
eta[k] = 1 / y[k]

ek = np.eye(n) # matrice identitate
ek[:,k] = eta # coloana k este inlocuita cu eta

btilda1 = ek @ b1
print("inversa lui btilda este:\n", btilda1)

inversa lui btilda este:
 [[ 0.2        -0.2         0.        ]
 [ 0.          1.          0.        ]
 [ 0.         -0.66666667  0.33333333]]


In [9]:
2/3

0.6666666666666666